### ISSUE TITLE
(Feature Request) Insert or Type the Emoji instead of copying to clipboard on <Enter>

### ISSUE THREAD

**Issue by Natedude** [techouse/alfred-emoji#6]
Is there a way of doing this?

I noticed most Alfred emoji workflows only copy to clipboard and I am wondering if there is some issue with doing that related to the expanding of snippets or something.

If this is possible, how could I alter the workflow so that this Inserts or Types the Emoji instead of copying to clipboard on <Enter>?

**Comment by techouse** [comment]
Hey,

This already works.

<img width="847" alt="image" src="https://github.com/techouse/alfred-emoji/assets/1174328/ea2a0adf-3c47-4cef-a8cf-abe071fb6d2d">

Check the [FAQ](https://github.com/techouse/alfred-emoji#modifier-keys) and make sure that you have the latest version.
